task_attributes:
    vqa:
        datasets:
        - textvqa
        dataset_size_proportional_sampling: true
        dataset_attributes:
            textvqa:
                data_root_dir: ../data
                image_depth_first: false
                slow_read: false
                image_features:
                    train:
                    - open_images/detectron_fix_100/fc6/train,open_images/resnet152/train
                    val:
                    - open_images/detectron_fix_100/fc6/train,open_images/resnet152/train
                    test:
                    - open_images/detectron_fix_100/fc6/train,open_images/resnet152/train
                imdb_files:
                    train:
                    - imdb/textvqa_0.5/imdb_textvqa_train.npy
                    val:
                    - imdb/textvqa_0.5/imdb_textvqa_val.npy
                    test:
                    - imdb/textvqa_0.5/imdb_textvqa_val.npy
                features_max_len: 137
                processors:
                  text_processor:
                    type: vocab
                    params:
                      max_length: 14
                      vocab:
                        type: intersected
                        embedding_name: glove.6B.300d
                        vocab_file: vocabs/vocabulary_100k.txt
                  answer_processor:
                    type: soft_copy_answer
                    params:
                      vocab_file: vocabs/answers_textvqa_more_than_1.txt
                      preprocessor:
                        type: simple_word
                        params: {}
                      context_preprocessor:
                        type: simple_word
                        params: {}
                      max_length: 50
                      num_answers: 10
                      use_soft_copy: false
                  context_processor:
                    type: fasttext
                    params:
                      max_length: 50
                      model_file: .vector_cache/wiki.en.bin
                  ocr_token_processor:
                    type: simple_word
                    params: {}
                  bbox_processor:
                    type: bbox
                    params:
                      max_length: 50
                return_info: true
                # Return OCR information
                use_ocr: true
                # Return spatial information of OCR tokens if present
                use_ocr_info: false
training_parameters:
    monitored_metric: textvqa_vqa_accuracy
    metric_minimize: false
