task_attributes:
    vqa:
        datasets:
        - vizwiz
        dataset_size_proportional_sampling: true
        dataset_attributes:
            vizwiz:
                data_root_dir: ../data
                image_depth_first: false
                slow_read: false
                image_features:
                    train:
                    - vizwiz/detectron_fix_100/fc6/train,vizwiz/resnet152/train
                    val:
                    - vizwiz/detectron_fix_100/fc6/val,vizwiz/resnet152/val
                    test:
                    - vizwiz/detectron_fix_100/fc6/test,vizwiz/resnet152/test
                imdb_files:
                    train:
                    - imdb/vizwiz/imdb_vizwiz_train.npy
                    val:
                    - imdb/vizwiz/imdb_vizwiz_val.npy
                    test:
                    - imdb/vizwiz/imdb_vizwiz_test.npy
                features_max_len: 100
                processors:
                  text_processor:
                    type: glove
                    params:
                      max_length: 14
                      vocab:
                        type: intersected
                        embedding_name: glove.6B.300d
                        vocab_file: vocabs/vocabulary_100k.txt
                  answer_processor:
                    type: soft_copy_answer
                    params:
                      vocab_file: vocabs/answers_vizwiz_7k.txt
                      preprocessor:
                        type: simple_word
                        params: {}
                      context_preprocessor:
                        type: simple_word
                        params: {}
                      max_length: 50
                      num_answers: 10
                      use_soft_copy: false
                  context_processor:
                    type: fasttext
                    params:
                      max_length: 50
                      model_file: .vector_cache/wiki.en.bin
                  ocr_token_processor:
                    type: simple_word
                    params: {}
                  bbox_processor:
                    type: bbox
                    params:
                      max_length: 50
                metrics:
                - vqa_accuracy
                loss: logit_bce
                return_info: true
                # Return OCR information
                use_ocr: true
                # Return spatial information of OCR tokens if present
                use_ocr_info: false
training_parameters:
    monitored_metric: vizwiz_vqa_accuracy
    metric_minimize: false
