task_attributes:
    vqa:
        datasets:
        - vqa2
        dataset_size_proportional_sampling: true
        dataset_attributes:
            vqa2:
                data_root_dir: ../data
                image_depth_first: false
                slow_read: false
                image_features:
                    train:
                    - coco/detectron_fix_100/fc6/train_val_2014,coco/resnet152/train_val_2014
                    - coco/detectron_fix_100/fc6/val2014,coco/resnet152/val2014
                    val:
                    - coco/detectron_fix_100/fc6/train_val_2014,coco/resnet152/train_val_2014
                    test:
                    - coco/detectron_fix_100/fc6/test2015,coco/resnet152/test2015
                imdb_files:
                    train:
                    - imdb/imdb_train2014.npy
                    - imdb/imdb_val2014.npy
                    val:
                    - imdb/imdb_minival2014.npy
                    test:
                    - imdb/imdb_test2015.npy
                features_max_len: 100
                processors:
                  text_processor:
                    type: glove
                    params:
                      max_length: 14
                      vocab:
                        type: intersected
                        embedding_name: glove.6B.300d
                        vocab_file:  vocabulary_vqa.txt
                  answer_processor:
                    type: vqa_answer
                    params:
                      vocab_file: answers_vqa.txt
                      preprocessor:
                        type: simple_word
                        params: {}
                metrics:
                - vqa_accuracy
                loss: logit_bce
                return_info: true
training_parameters:
    monitored_metric: vqa2_vqa_accuracy
    metric_minimize: false
